Revert "Fix dependabot format error [Skip-CI] (#76)"
This reverts commit 5cfa0e9e85c838c5dd168f615374738a1319b4c9.

diff --git a/.github/workflows/branch-name.yml b/.github/workflows/branch-name.yml
--- a/.github/workflows/branch-name.yml
+++ b/.github/workflows/branch-name.yml
@@ -11,10 +11,10 @@ jobs:
       - name: Validate branch name
         run: |
           BRANCH_NAME="${GITHUB_HEAD_REF}"
-          if [[ "$BRANCH_NAME" =~ ^dependabot/.+$ ]] &&
-            [[ ! "$BRANCH_NAME" =~ ^(feat|fix|refactor|chore)/[a-z0-9-]+$ ]]; then
-                echo "Invalid branch name: $BRANCH_NAME"
-                echo "Allowed patterns:"
-                echo "feat/*, fix/*, refactor/*, chore/*, dependabot/*"
-                exit 1
+
+          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|refactor|chore|dependabot)/[a-z0-9-]+$ ]]; then
+            echo "Invalid branch name: $BRANCH_NAME"
+            echo "Allowed patterns:"
+            echo "feat/*, fix/*, refactor/*, chore/*, dependabot/*"
+            exit 1
           fi
